### ISSUE TITLE
Fake dns records appearing on my domain

### ISSUE THREAD

**Issue by alx-alexpark** [obl-ong/admin#10] opened 2023-08-11 19:43 UTC
Seen many times, other people's DNS records show up on my domain, disappearing when I refresh the page.
![image](https://github.com/obl-ong/admin/assets/63802868/2ad45356-747d-483a-b982-cbd0b4c8bb83)
![image](https://github.com/obl-ong/admin/assets/63802868/a1e9a792-3427-44fe-9ed7-87ac6c53dc78)

**Comment by reesericci** [comment] 2023-12-27 02:11
Has this been seen recently?

**Comment by reesericci** [comment] 2024-02-07 07:02
I was able to finally reproduce this bug!! It's because when a new record is created, the turbo stream update is broadcasted to _all_ users -- it isn't scoped to just the current domain. 

Screencast:

[Screencast from 2024-02-07 00-57-22.webm](https://github.com/obl-ong/admin/assets/19589006/9ce88d5c-8813-4b6e-9ad0-ea6152a35ea9)

**Comment by reesericci** [comment] 2024-02-07 07:50
Fixed in [3f6f2e](https://github.com/obl-ong/admin/commit/3f6f2e9a8c9f7a68b4f85836081229eab814e588)

**Comment by reesericci** [comment] 2024-02-07 07:50
Fixed in [3f6f2e](https://github.com/obl-ong/admin/commit/3f6f2e9a8c9f7a68b4f85836081229eab814e588)

**Closed by reesericci** 2024-02-07 07:50 UTC
Labels: bug
